const dominios = {
    ID_ROL_PACIENTES: "637771c7902d6af0bf6b4d53",
    ESTADO_ACTIVO_USUARIO: 1,
    ESTADO_INACTIVO_USUARIO: 2,
    ESTADO_ACTIVO_ROL: 1,
    ESTADO_INACTIVO_ROL: 2
}
export default dominios;